### ISSUE TITLE
[Bug]: Map failed to initialize and unable to upload data

### ISSUE THREAD

**Issue by fu050409** [yaoshiu/pretty-der6y#26] opened 2024-08-30 06:43 UTC
Map now get a critical error, neither install the release or build the project manually can run properly:

![image](https://github.com/user-attachments/assets/595e040f-8b57-4281-9e46-cc93a5243015)

It seems only try to select a exsit file to upload data but I have no idea of the file format.

Environment:

```
Windows 11 24H2
Kali Linux 24.04
```

**Comment by yaoshiu** [comment] 2024-08-30 07:15
When initialized, `LeafMap` will request your location information and then display a map centered around your location. If authorization to access your location is not granted, `LeafMap` may not initialize correctly.

**Comment by yaoshiu** [comment] 2024-08-30 07:16
Could you provide more specific information? Did Pretty Der6y request your location information before initialization?

**Comment by yaoshiu** [comment] 2024-08-30 07:19
> It seems only try to select a exsit file to upload data but I have no idea of the file format.

The file format is GEOJSON. And an example is provided in the assets folder.

**Comment by fu050409** [comment] 2024-08-30 14:22
Have you tried to run it cross platforms? I can't run with the release in my kali linux virtual machine in VMware.

**Comment by yaoshiu** [comment] 2024-08-30 16:30
> Have you tried to run it cross platforms? I can't run with the release in my kali linux virtual machine in VMware.

Haven't tested on a VM yet but it works perfectly on my Gentoo. Can you show me the outputs when running in the console?

**Comment by yaoshiu** [comment] 2024-08-30 22:49
Seems like a issue with Tauri and webviews, except for the newest Windows webview.

I've just committed some changes to provide a fallback method for retrieving the location. Check the latest master branch if it's convenient.

**Comment by fu050409** [comment] 2024-08-31 07:55
It's odd more than before, after i granted the permission, the program told me that i had prevented the permission.

![image](https://github.com/user-attachments/assets/06959678-adcb-4875-a893-0c54db3be6aa)

**Comment by fu050409** [comment] 2024-08-31 07:59
I'm sure that i clicked accept:

![image](https://github.com/user-attachments/assets/f4327362-6c90-4cb0-ab47-899ce79c5bd8)

**Comment by yaoshiu** [comment] 2024-08-31 08:44
Maybe try updating your webview version.

**Comment by fu050409** [comment] 2024-08-31 08:46
> Maybe try updating your webview version.

I have the latest webview installed in fact.

**Comment by yaoshiu** [comment] 2024-08-31 10:07
> It's odd more than before, after i granted the permission, the program told me that i had prevented the permission.
> 
> ![image](https://private-user-images.githubusercontent.com/46275354/363398109-06959678-adcb-4875-a893-0c54db3be6aa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUwOTg3MjEsIm5iZiI6MTcyNTA5ODQyMSwicGF0aCI6Ii80NjI3NTM1NC8zNjMzOTgxMDktMDY5NTk2NzgtYWRjYi00ODc1LWE4OTMtMGM1NGRiM2JlNmFhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODMxVDEwMDAyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE1MTY3MjMzNTVjYTBmMGU5NGVhMWI2MDdiYmRhYzMyMWY2MzZhMDg1NzNjYzM2OTA1MjdmMDk0Y2JjOGIyN2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.EHSq3SW4ngDLh712mUGYHHdLx5uaFVzIRXWmle8MH8Q)

This is what should happen when the permission request is refused. I'm pretty sure that pretty-der6y is not to blame, as the error is thrown by the built-in `navigator`.

Maybe check your system settings to see if the location services is on in your system.

**Comment by fu050409** [comment] 2024-08-31 11:07
I have to tell you the not so good news, after I checked my device it seems to have no issues with permissions and location services. In the meantime I tried running our distro on other devices (including VMs) but it didn't work either. For what it's worth, I can use geolocation fine in my Chrome and Edge browsers.

**Comment by yaoshiu** [comment] 2024-08-31 11:27
>  it doesn't respond to any of my actions.

What do you mean by "it does not respond"？Did it hang when you clicked the uploader? Or did the map stop updating when you uploaded a geojson?

**Comment by fu050409** [comment] 2024-08-31 11:34
Not really. It may be that I have yet to understand how our program works, but at the moment it doesn't look like our map component is doing anything practical? I see in `README.md`, we should generate a custom geojson route file manaully and drag the file into our distro window.

**Comment by fu050409** [comment] 2024-08-31 11:39
> Also, the site [georoute.io](https://georoute.io) in `README.md` is unreachable whatever a proxy is enabled or not.

This is damnly critical. Generating a geojson file manuly is painful, whether it's me or a regular user. But unfortunately, the site seems to be dead. I can neither directly connect to the site nor use a proxy.

**Comment by yaoshiu** [comment] 2024-08-31 11:50
> Generating a geojson file manually is painful, whether it's me or a regular user.

It truely is, which is why we provided an example that is ready for SWPU users. PRS for other locations are welcome as well.

**Comment by yaoshiu** [comment] 2024-08-31 12:03
> but at the moment it doesn't look like our map component is doing anything practical?

The `LeafletMap` is essentially more of a visual aid; it simply provides a view of the GeoJSON file you uploaded. It does not support creating or modifying a GeoJSON file directly, nor do I plan to add such functionality, as it would introduce unnecessary complexity. Moreover, I don't believe anyone would want to upload running data without having the route file prepared in advance.

**Comment by yaoshiu** [comment] 2024-08-31 14:49
Now that the problem is fixed, I will close this issue

**Closed by yaoshiu** 2024-08-31 14:49 UTC
